server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/v5
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  type-aliases-package: com.ylht.pojo
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
logging:
  config: classpath:logback-boot.xml
